# Generated by Django 5.0.3 on 2024-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_chunkedupload_delete_mediauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
